name: Build
on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      # Can't expand the matrix due to the flakiness of the CI infra
      matrix:
        os:
        - macos-12 # because macOS 14, 15 does not support build on nested virtualization
        go:
        - '^1.23'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: Code-Hex/vz
          ref: fix/175
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Download Linux kernel
        run: make download_kernel
      - name: Build Linux
        run: make -C example/linux
      #- run: make test
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
      #  timeout-minutes: 15
