name: Build
on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      # Can't expand the matrix due to the flakiness of the CI infra
      matrix:
        os:
        - macos-13 # because macOS 14, 15 does not support build on nested virtualization
        go:
        - '^1.23'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: Code-Hex/vz
          ref: add/attachmentWasDisconnectedWithError
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Download Linux kernel
        run: make download_kernel
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
